# Generated by Django 3.1.2 on 2021-12-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iraq', '0002_auto_20211229_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='intity',
            name='email',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intity',
            name='facebook',
            field=models.URLField(default='https://www.facebook.com/', max_length=255),
        ),
    ]
